### PR TITLE
Changes to use LArSoft v9

### PR DESCRIPTION
**Pull request by knoepfel**
This includes all of the thread-safety changes for detector clocks/properties services.

Unfortunately, an earlier version of this PR (#2) was prematurely merged, thus confusing the Git history.  The changes in this PR include all changes required for use LArSoft v9.  Careful resolutions of commit conflicts will be required because of the commit confusion.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
Hmm... is there something that tells me what resolutions I should be accepting for the changes to services? I am hoping this is not going to require a big effort - time being precious as we are trying to sort out start up issues right now...

**Comment by knoepfel** [comment]
Let me experiment a little, @SFBayLaser.  I suspect the merge will need to be done by hand offline...but it might be simple.  I'll  let you know once I learn more.

**Comment by knoepfel** [comment]
Okay, try again @SFBayLaser.  Should be good to go now.

**Comment by knoepfel** [comment]
In other words, a direct merge with develop should be fine now.

**Pull request merged**
