### PR TITLE
Trigger efficiency tree: adopted association traversal utility

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This is a technical change: the module used to extract information from Stage1 _art_/ROOT files into a custom analysis tree uses chained associations to get the time of a track. It used to do the traversal in-house, now it uses the utility introduced in SBNSoftware/icarusalg#69.

Tested that it gives the same results as before.
Reviewers... @jzettle because he used and coauthored the module.

Note: it might conflict with #602 — in that case, merge that one first and then knock at my door.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#69

**Review by jzettle — COMMENTED** [review]
I guess we should follow the idea in the PR, if it conflicts with #602, then work with Gianluca to fix it

**Review by jzettle — APPROVED** [review]

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_01 SBNSoftware/sbncode@v09_75_01_01 SBNSoftware/sbnanaobj@v09_21_02 SBNSoftware/sbndaq-artdaq-core@v1_08_00of0 SBNSoftware/sbnobj@v09_17_03 SBNSoftware/icarusalg#69

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_01 SBNSoftware/sbncode@v09_75_01_01 SBNSoftware/sbnanaobj@v09_21_02 SBNSoftware/sbndaq-artdaq-core@v1_08_00of0 SBNSoftware/sbnobj@v09_17_03 SBNSoftware/icarusalg#69

**Pull request merged**
