### PR TITLE
fcl additions for stage1+larcv

### PR DESCRIPTION
**Pull request by yeonjaej**
Fcl additions for 
Stage1+larcv processing for
- MPVMPR and Nu(generator) only.  

@SFBayLaser and Francois should review this.

### CODE REVIEW

**Review by SFBayLaser — COMMENTED** [review]
No problem with these additions! I think we need to watch merging since I just added a PR to fix the hit finding and it makes some mods which I hope don't conflict. I will try merging your PR into my develop area to make sure that does not happen.

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_84_00 SBNSoftware/sbncode@v09_84_00_01 SBNSoftware/sbnanaobj@v09_22_01 SBNSoftware/sbndaq-artdaq-core@v1_08_00of4 SBNSoftware/sbnobj@v09_18_01_01

**Review by SFBayLaser — APPROVED** [review]
One of the things I dislike about fhicl is that we have to make a new file to change just a few parameters... which means we fill our folders with lots of files and it becomes confusing to know what is what... sigh... nothing can be done about that now.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
