### PR TITLE
Accommodate breaking changes in geometry

### PR DESCRIPTION
**Pull request by knoepfel**
Pursuant to LArSoft/larcorealg#34.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_01 SBNSoftware/icarusalg#63

**Review by PetrilloAtWork — APPROVED** [review]
All looks good (more @auto@ than I like, but that's just me).
Thanks to @knoepfel for the painstaking effort!

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_03 SBNSoftware/icarusalg#63

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#63

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_03 SBNSoftware/sbncode@v09_65_03 SBNSoftware/sbnanaobj@v09_20_02 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_04 SBNSoftware/icarusalg#63

**Pull request merged**
