### PR TITLE
Update detector variation fcl files to fix bug in induction 1 gain value and clean up for BNB analysis

### PR DESCRIPTION
**Pull request by jzettle**
This pull request covers updates to the detector variation fhicl files to set up the new suite of detector variations. The major changes here represent an update to the induction 1 plane gain value to match the TPC signal shapes required for the analysis (untuned ind1, tuned ind2, coll). The previous variation samples had an induction 1 plane gain that was 50% lower than this new value and matched the tuned induction 1 signal shapes. I have tested one of these locally and was able to run the chain on one of the CV files. We are also attempting a test production of one of these variations in order to make sure the official production is also successful from these changes.

Reminder this chain splits the g4 stage into two parts in order to use the identical `gen` and `largeant` step in the CV and all the variation samples.  

Additionally this cleans up the area in icaruscode/fcl/syst_variations to only include fhicl files we intend to use or make up a possible backup solution in case something does not come together in time. The files within this release are as follows:
fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_cohm(p)1_icarus.fcl: TPC coherent noise variations based on a study by @justinjmueller of the channel-to-channel variations of the noise across the detector
 fcl/syst_variations/detsim_2d_TPCnoise_refactored_variation_intm(p)1_icarus.fcl: TPC intrinsic noise variations based on a study by @justinjmueller of the channel-to-channel variations of the noise across the detector
fcl/syst_variations/detsim_2d_icarus_refactored_variation_ind0gainhi(low).fcl: Induction 1 plane gain variation of +/- 15%. The updates here change the value from the previous iteration in order to account for the updated CV gain value
fcl/syst_variations/detsim_2d_icarus_refactored_variation_run2lifetimelow(hi).fcl: Electron lifetime variation setting the electron lifetime in the detsim to 4(8) ms
fcl/syst_variations/g4_icarus_qe_variations.fcl: Scintillation light model variation which lowers the QE of the PMTs to 4% from the nominal 7.3%, from studies within the OpReco group this change allows the integrated light of the hits to agree between data/MC but then the amplitude disagrees.
fcl/syst_variations/g4_icarus_step2_refactored_recombmodel_variations.fcl: Turns on the ellipsoidal modified box model for recombination instead of the modified box model.

Other important files are:
fcl/syst_variations/refactored_g4_icarus_step1.fcl: First step of g4 stage that only runs the `largeant` process
fcl/syst_variations/refactored_g4_icarus_step2.fcl: Second step of g4 stage that runs the rest of the original g4 stage
fcl/syst_variations/scrub_stage1_variations_icarus.fcl: Takes the stage1 files from the CV sample and removes the data products until g4step1 

The last part to note here is that in order to run the variation process successfully having already run the full production chain on the CV sample, we need fhicl files that do nothing but change the art `process_name` and run the identical fhicl file as the nominal. If we run the same art process twice, it will fail so we have no choice but to include these files. 

The CV pathway is now this one:
gen: prodcorsika_bnb_genie_protononly_icarus.fcl
filter: filter_genie_active_icarus.fcl
g4step1: refactored_g4_icarus_step1.fcl
g4step2: refactored_g4_icarus_step2.fcl
detsim: detsim_2d_icarus_refactored.fcl
stage0: stage0_run2_icarus_mc_refactored.fcl 
stage1: stage1_run2_1d_larcv_icarus_MC.fcl
caf: cafmakerjob_icarus_detsim2d_systtools_and_fluxwgt.fcl

The variation pathway that does not change anything is (usually replace either g4step2 or detsim fhicl with the correct variation for each variation sample):
scrub: scrub_stage1_variations_icarus.fcl
g4step2: refactored_g4_icarus_step2_variations.fcl
detsim: detsim_2d_variation_refactored_icarus.fcl
stage0: stage0_variation_icarus_refactored.fcl
stage1: stage1_variation_icarus_larcv.fcl
caf: cafmakerjob_icarus_detsim2d.fcl

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_89_01 SBNSoftware/sbndaq-artdaq-core@v1_09_00of1 SBNSoftware/sbncode@v09_89_01_01 SBNSoftware/sbnanaobj@v09_23_00_01 SBNSoftware/sbnobj@v09_19_00_01 SBNSoftware/icarus_signal_processing@v09_88_00_02 SBNSoftware/icarusalg@v09_88_00_02 SBNSoftware/icarusutil@v09_88_00_02

**Comment by jzettle** [comment]
Added a lot of details and a few more people who might want to look this over to make sure everything is in order and setup correctly.

**Comment by jzettle** [comment]
Make a small change to make each of the detsim variation fhicls inherit from `detsim_2d_icarus_refactored.fcl` instead of the `detsim_2d_variations_refactored_icarus.fcl` in the variation directory. It is functionally equivalent, but not needed so removing a layer of possible issue. Are people able to review this?

**Review by cfarnese — APPROVED** [review]
I just looked at the fhicl changes and they seems to me ok, no direct test made on these PR

**Review by SFBayLaser — APPROVED** [review]
I am good with the reorganization/deletion. In a visual review I don't see issues with the fhicl files (or obvious ones)

**Review by etworcester — APPROVED** [review]
This seems to me to reflect what we have talked about, but I don't feel expert enough in the workflow to comment on the details

**Comment by mrmooney** [comment]
This looks fine to me, aside from the 6 ms lifetime that we decided today to use.  Is that going to be put in place?

**Pull request merged**
