### PR TITLE
Tuned Simulated Field Responses

### PR DESCRIPTION
**Pull request by gputnam**
Extends the WireCell jsonnet configuration to make more parameters configurable. Adds in a configuration to simulate the "tuned" signal response.

I have validated that the nominal configuration produces the exact same JSON output as before this PR.

Notes:
-I am putting this into draft form for now since we still may be tuning some things like the gain
-This will also require an update to icarus_data to add in the new field response file

### CODE REVIEW

**Comment by gputnam** [comment]
@rennney thanks! I think you were right to be worried about the elec response parameters. I just checked and found an issue, which is now fixed. And I'll update the config you linked.

**Comment by gputnam** [comment]
This is ready to go -- for validation, see docdb 31264.

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_03 SBNSoftware/sbnanaobj@v09_20_06 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_03 SBNSoftware/sbnanaobj@v09_20_06 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Pull request merged**
