### PR TITLE
Trigger efficiency tree maker updates

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This update to the analysis module and workflow used for trigger efficiency analyses includes:
 * fixes for track flipping (when upgoing tracks are flipped, hit and calorimetry info are now corrected)
 * addition of information _whether_ the track was flipped
 * allowed time interval for each track according to its hits (requires SBNSoftware/icarusalg#68)
 * hit tick range

Expect a production PR too.

Reviewers... hmm. @jzettle, try what you can, or please suggest another reviewer.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#68

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_03 SBNSoftware/icarusalg#68

**Review by jzettle — APPROVED** [review]

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_01 SBNSoftware/sbncode@v09_75_01_01 SBNSoftware/sbnanaobj@v09_21_02 SBNSoftware/sbndaq-artdaq-core@v1_08_00of0 SBNSoftware/sbnobj@v09_17_03 SBNSoftware/icarusalg#68

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#68

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#68

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#68

**Pull request merged**
