### PR TITLE
Run CRT Matching at CAF-making stage in data/MC

### PR DESCRIPTION
**Pull request by gputnam**

### CODE REVIEW

**Review by tboone0042 — APPROVED** [review]
Looks fine to me! I see nothing that conflicts with anything I'm aware of.

**Comment by cerati** [comment]
@gputnam, is this PR related to https://github.com/SBNSoftware/sbncode/pull/316?

**Comment by gputnam** [comment]
@cerati they're both related to the CRT but kind of orthogonal. This one runs our CRT-TPC matching in the standard reco chain.

The other one fixes how times are referenced in CAFMaker for the CRT. 

Both of them are needed to get the CRT matching working in the CAFs, but they are orthogonal PRs that can be merged independently.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#61

**Review by jzettle — APPROVED** [review]

**Pull request merged**
