### PR TITLE
Generation Configurations for ALP model in ICARUS

### PR DESCRIPTION
**Pull request by gputnam**
Depends on https://github.com/SBNSoftware/sbncode/pull/339.

This PR provides configurations to generate ALP and HNL decaysin ICARUS MC enabled by the corresponding update to sbncode.

NOTE: this is not needed for the upcoming MCP. It is intended to be merged once the corresponding sbncode PR is merged.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/sbncode#339

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/sbncode#339 LArSoft/lar*@LARSOFT_SUITE_v09_68_00

**Comment by SFBayLaser** [comment]
Is it possible for the PR submitter to be more verbose in his description of what this PR is meant to do? I get the link back to sbncode, but maybe a few more words to help for the future when people are reviewing past PRs to understand what various changes were for. Does not need to be a full publication but maybe a bit more descriptive? Thanks.

**Comment by gputnam** [comment]
@SFBayLaser fixed.

**Comment by gputnam** [comment]
@mmrosenberg the sbncode PR has been merged, this should be ready to go.

**Pull request merged**
