### PR TITLE
Discriminated PMT waveforms in Stage0 (SBN2022A) [2/2]

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This request mirrors the feature of #362 into the `release/SBN2022A` branch.
See that pull request for details.
The pull request on this branch requires also:
1. changes in `icarusalg` that are already in `develop` but not in the `release/SBN2022A` branch (twin pull request SBNSoftware/icarusalg#48)
2. supporting changes in `icaruscode` that are already in `develop` but not in the `release/SBN2022A` branch (most were introduced with #342 and they constitute the bulk of _this_ pull request)

Most of these changes are not necessary to run Stage0, but rather to be able to run the trigger emulation afterward.

List of commits, courtesy of `gh`:
- Patch tag to include Animesh's generators
- Why did this have to change? Compiles now...
- Apparently I cannot add another ".01" to a tag... so doing it a bit differently.
- Set the patch tag, will require some hand editing?
- Ok, this is the correct convention - we will go with v09_37_01_02p01
- Porting Mike Mooney's fix for space charge to the production branch
- Applying Mike Mooney style fix for wirecell offset
- patch release with Mike's space charge fix
- Fixing reference to icarus_data
- Backing out the space charge fix on the production branch while moving to latest sbncode release
- Get the right version in the right place
- Porting Mike's fixes back into the production branch. This process is really prone to error...
- Putting back all of the SCE fixes and preparing to tag
- Add Updated GARFIELD simulation
- Need this one too
- updated icaruscode tags to v09_37_01_03p02 for production patch release
- Renamed sbn::PMTcoverageInfo into sbn::OpDetWaveformMeta
- LVDSgates module now requires waveform metadata instead of waveforms.
- fixup
- SlidingWindowTrigger module now requires waveform metadata instead of waveforms.
- Migrated all the main trigger modules to use tracking trigger gates
- Removed deprecated data structures from trigger code.
- Removed obsolete assertion
- Removed obsolete assertion (another one)
- LVDS width configuration parameter turned into a time
- Stage0 configuration now includes discriminating PMT waveforms

## Testing

Tested on 2 (two) data events from a run `7033` NuMI file and one simulated (`DetSim`) event.

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
I apologise for wasting you reviewer your time... I have added the same feature in MC Stage0 processing.
Now I consider the feature complete.

**Review by SFBayLaser — APPROVED** [review]
This is meant to mirror the updates to the master/develop branch but looks to be more substantial. It looks like a lot more backporting needed which explains a lot of files. But it looks to me that this is good to go will will approve

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_37_01_01 LArSoft/webevd@LARSOFT_SUITE_v09_37_01_01 SBNSoftware/sbndaq-artdaq-core@v1_00_00of0 SBNSoftware/sbn*release/SBN2021C SBNSoftware/icarus_data@v09_42_00 SBNSoftware/icarus*@v09_37_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_37_01_01 LArSoft/webevd@LARSOFT_SUITE_v09_37_01_01 SBNSoftware/sbndaq-artdaq-core@v1_00_00of0 SBNSoftware/sbn*@release/SBN2021C SBNSoftware/icarus_data@v09_42_00 SBNSoftware/icarus*@v09_37_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_37_01_01 LArSoft/webevd@LARSOFT_SUITE_v09_37_01_01 SBNSoftware/sbndaq-artdaq-core@v1_00_00of0 SBNSoftware/sbn*@release/SBN2021C SBNSoftware/icarus_data@v09_44_00 SBNSoftware/icarusalg@release/SBN2022A SBNSoftware/icarus*@v09_37_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_37_01_02 LArSoft/webevd@LARSOFT_SUITE_v09_37_01_02 SBNSoftware/sbndaq-artdaq-core@v1_00_00of2 SBNSoftware/sbncode@v09_37_02_01 SBNSoftware/sbnobj@v09_12_12 SBNSoftware/sbnanaobj@v09_17_06_04 SBNSoftware/icarus_data@v09_44_00 SBNSoftware/icarusalg@release/SBN2022A SBNSoftware/icarus*@v09_37_01

**Pull request merged**
