### PR TITLE
Fixed CAF making jobs with generator systematics

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Recently I reworked the random number service configuration and at the same time removed the configuration of the random services from the places where it is not supposed to belong.
CAF making is one of them, since it's about translation of data from one format to another.
Unfortunately CAF making currently does more than just translation, and in particular for simulation input it runs a generation-class process, the stochastic extraction of generation parameters and the computation of the weights bridging the extracted parameters to the ones chosen by the experiment as the best ones. These jobs were broken by my changes.

This pull request simply adds the configuration of the required services to the two CAF making jobs including weight generation that I could find.
It is a non-breaking bug fix.

### CODE REVIEW

**Comment by jedori0228** [comment]
I checked `fcl/caf/cafmakerjob_icarus_sce_genie.fcl` and `fcl/caf/cafmakerjob_icarus_sce_genie_and_fluxwgt.fcl`, which are the ones that are updated, run fine, but the other MC CAFMaking fcls (e.g., `cafmakerjob_icarus_sce.fcl`) still have issues, should we also add those lines to them?

**Comment by Ooohu** [comment]
It looks like this is targeting the random services only; other issues occurred within `afmakerjob_icarus_sce.fcl` (I am not aware of what are they) may be fixed in a new PR?

**Comment by jedori0228** [comment]
Also `cafmakerjob_icarus_evtw.fcl`

**Comment by PetrilloAtWork** [comment]
I did not realise that
1. the simplified ("fake") reconstruction happens in the module and uses random numbers,
2. the blinding decision is also stochastic (subject of issue SBNSoftware/sbncode#306).

With this, the random engines are needed in both MC and data.

**Comment by PetrilloAtWork** [comment]
Now this branch restores the random number services in all `CAFMaker` jobs. Thank you for spotting the fact that the issue was more spread than I thought.

> It looks like this is targeting the random services only; other issues occurred within `cafmakerjob_icarus_sce.fcl` (I am not aware of what are they) may be fixed in a new PR?

I am not sure which other issues you are referring to. If they are about random streams, I should fix them here.
Otherwise... it depends. Please point me to the report for such issues if there are any.

**Review by jedori0228 — APPROVED** [review]
I tested cafmakers and runs fine.

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
