### PR TITLE
Feature/aaduszki crt

### PR DESCRIPTION
**Pull request by aaduszki**
Class providing access to any version and type of side/top raw CRT data.

### CODE REVIEW

**Comment by wesketchum** [comment]
@SFBayLaser is there anything from keeping this PR from getting merged in?

**Comment by SFBayLaser** [comment]
Somehow I have a recollection that I was waiting for word from Antoni that this was really ready to go (see comment in list of items that says "not yet ready").

**Comment by wesketchum** [comment]
Thanks. @aaduszki, this is ready to go, right?

**Comment by aaduszki** [comment]
Yes. Sorry for miscommunication. I thought that when I request a pull request it will be clear the work is complete.

**Comment by SFBayLaser** [comment]
Ok, my bad. I was led astray by the comment in the PR. Will include next release.

Sent from my iPad

On Feb 25, 2021, at 1:10 PM, aaduszki <notifications@github.com> wrote:

﻿

Yes. Sorry for miscommunication. I thought that when I request a pull request it will be clear the work is complete.

**Pull request merged**
