### PR TITLE
improvements on CRT hit and track reconstruction algorithm

### PR DESCRIPTION
**Pull request by biswaranjan91**

### CODE REVIEW

**Comment by gputnam** [comment]
Hi! A question -- are these updates intended to be included in the upcoming ICARUS MCP? And if so are there configuration changes that should be propagated to the MC reco?

**Comment by biswaranjan91** [comment]
Hi Gray,
Yes, it will be included in the next release and configuration file is changed with two parameters. Thank you.

**Comment by jzennamo** [comment]
I added @SFBayLaser and @PetrilloAtWork as reviewers as they are trying to get the reco fcls together, they should reassign reviewers as they see fit. Thanks!

**Comment by SFBayLaser** [comment]
I removed myself as a reviewer as I am not expert enough on this code base to be able to offer substantial comments on the changes. Perhaps we need suggestions for reviewers for CRT related code?

**Comment by SFBayLaser** [comment]
Ok, crash and burn... here we go!

**Comment by PetrilloAtWork** [comment]
Reviewing this code would require a lot of time (for me at least). I recommend somebody with preexisting expertise, or in alternative to allocate two weeks of review time.

**Pull request merged**
