### PR TITLE
Set dropped MCParticle label properly

### PR DESCRIPTION
**Pull request by bear-is-asleep**

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Pull request merged**
