### PR TITLE
Feature/cerati crtpmtfilter fcl

### PR DESCRIPTION
**Pull request by cerati**
This PR adds a fcl to run the CRT-PMT filter and copy forward the TPC RAW data only for events that pass the filter.
A producer module to make this copy is added as well.

The goal is to be able to reduce the size of the RAW data we need to process, starting from the data we already collected and currently store on disk.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
Does it make more sense to keep the noise filtered RawDigits vs the original daq data? Meaning will the compressed RawDigits take less space that daq -or- is it more or less and even split?

**Comment by cerati** [comment]
> Does it make more sense to keep the noise filtered RawDigits vs the original daq data? Meaning will the compressed RawDigits take less space that daq -or- is it more or less and even split?

This fcl does not run noise filtering, the goal is to store the original daq data to be able to reprocess it from scratch. Is noise filtering stable enough that we'll never need to re-run it? In that case we could have another fcl that does that.

**Comment by SFBayLaser** [comment]
Ah, my mistake, I read "daq" (and read past its definition) and assumed the decoder.

**Comment by SFBayLaser** [comment]
Last question, what is run time for this? Next iteration of noise filtering has decode step down to 30 sec/event or less which is a fraction of the root output stage.... if that holds true on gpvms when why not run decode step and save RawDigits? Saves time for the processing... (though that will be dominated by 2D decon).

**Comment by cerati** [comment]
On icarubuild02 it takes 11 seconds per event on average for 50 events, including the root output which takes 4 seconds.

**Review by francescopoppi — APPROVED** [review]

**Comment by mmrosenberg** [comment]
trigger build

**Review by SFBayLaser — APPROVED** [review]

**Pull request merged**
