### PR TITLE
Fix cmake and build errors found in standalone build of icaruscode v09_63_00

### PR DESCRIPTION
**Pull request by gartung**
Add missing pkg_search_module needed by icarus_signal_processing target. Add missing link targets for header includes.

### CODE REVIEW

**Comment by gartung** [comment]
@miquelnebot

**Comment by gartung** [comment]
@rennney

**Comment by gartung** [comment]
trigger build

**Comment by gartung** [comment]
@rennney https://github.com/SBNSoftware/icaruscode/pull/490

**Comment by gartung** [comment]
The real fix for icarus_signal_processing https://github.com/SBNSoftware/icarus_signal_processing/pull/20

**Comment by gartung** [comment]
The CI failures are because memory and cpu usage are out of range.

**Comment by gartung** [comment]
Trigger build SBNSoftware/icarus_signal_processing#20

**Comment by rennney** [comment]
@gartung that is programmed to be a warning, not a fail, the fail massage from one of test logs (https://dbweb8.fnal.gov:8443/LarCI/app/ns:icarus/storage/docs/2022/11/16/stdout%23d8XYotd.log): 
: %MSG-s ArtException:  PostEndJob 16-Nov-2022 09:13:15 CST ModuleEndJob
172: ---- EventProcessorFailure BEGIN
173:   EventProcessor: an exception occurred during current event processing
174:   ---- ScheduleExecutionFailure BEGIN
175:     Path: ProcessingStopped.
176:     ---- FileReadError BEGIN
177:       ---- FatalRootError BEGIN
178:         Fatal Root Error: TNetXNGFile::ReadBuffer
179:         [FATAL] Connection error
180:         ROOT severity: 3000
181:       ---- FatalRootError END
182:       
183:       The above exception was thrown while processing module icaruscode/CRT/CRTDetSim/crtdaq run: 1 subRun: 0 event: 43
184:     ---- FileReadError END
185:     Exception going through path simulate
186:   ---- ScheduleExecutionFailure END
187: ---- EventProcessorFailure END
188: ---- FatalRootError BEGIN
189:   Fatal Root Error: TNetXNGFile::Close
190:   [FATAL] Connection error
191:   ROOT severity: 3000
192: ---- FatalRootError END
193: ---- FatalRootError BEGIN
194:   Fatal Root Error: TNetXNGFile::Close
195:   [FATAL] Connection error
196:   ROOT severity: 3000
197: ---- FatalRootError END
198: %MSG

**Comment by gartung** [comment]
Missing file?
`xroot://fndca1.fnal.gov:1095/pnfs/fnal.gov/usr/icarus/persistent/stash/ContinuousIntegration/reference/standard/detsim/intimecosmic_detsim_test_icaruscode_Reference.root`

**Comment by gartung** [comment]
Either the file is missing or the CI authentication did not work.
```
 RootInputFileSequence::initFile(): Input file xroot://fndca1.fnal.gov:1095/pnfs/fnal.gov/usr/icarus/persistent/stash/ContinuousIntegration/reference/standard/detsim/intimecosmic_detsim_test_icaruscode_Reference.root was not found or could not be opened.
296: ---- FileOpenError END
```

**Comment by brucehoward-physics** [comment]
Yeah I think Vito said till ~1pm CT in Slack

**Comment by vitodb** [comment]
> Yeah I think Vito said till ~1pm CT in Slack

correct, I'll send an update ASAP dCache maintenance is over

**Comment by vitodb** [comment]
> > Yeah I think Vito said till ~1pm CT in Slack
> 
> correct, I'll send an update ASAP dCache maintenance is over

dCache maintenance is over, CI builds should be able to access input/references from dCache

**Comment by gartung** [comment]
Trigger build SBNSoftware/icarus_signal_processing#20

**Comment by rennney** [comment]
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/20

**Comment by rennney** [comment]
trigger build https://github.com/SBNSoftware/icarus_signal_processing/pull/20

**Comment by PetrilloAtWork** [comment]
@gartung could you note in this thread where is the relevant information about your changes?
I.e. what the changes in this pull request mean and why they are needed.

**Comment by gartung** [comment]
@PetrilloAtWork This is needed until https://github.com/SBNSoftware/icarus_signal_processing/pull/20 is merged.

**Comment by gartung** [comment]
One of the icarus_signal_processing libraries links against the target for libfftw3, PkgConfig::FFTW3F. If a standalone build of icaruscode is done the cmake command fails with the error that the target is missing. The FindPackage(PkgConfig) and find_package_module(FFTW3F) are needed until https://github.com/SBNSoftware/icarus_signal_processing/pull/20 is merged.

**Comment by gartung** [comment]
https://github.com/SBNSoftware/icaruscode/pull/490 was requested for the same changes on the SBN2022B branch.

**Comment by PetrilloAtWork** [comment]
I think that one information I am missing is that the "link list" is not a link list any more, but it also ripples into header search paths. That would explain the appearance of targets that were missing because only template header files were used from them.

**Comment by gartung** [comment]
Yes. I just helped Terry Usher to diagnose a problem with building icaruscode/TPC/Utilities which was a missing target.

**Comment by gartung** [comment]
If you merge the pull request for icarus_signal_processing together with this on then the find_package(PkgConfig) is not needed in this pull request.

**Comment by rennney** [comment]
I am planning to merge them together if that is ok

**Comment by gartung** [comment]
OK. I pushed the change.

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarus_signal_processing#20

**Pull request merged**
