### PR TITLE
Encode PMT channel mapping DB key in the interface to DB

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This is an implementation of the proposal in icaruscode issue #151.

### CODE REVIEW

**Review by wesketchum — APPROVED** [review]
This looks fine to me. One thing is that I think asserts will be ignored in prof builds? If we want those in place, we may want to consider throwing exceptions instead? Could be wrong there though.

**Comment by PetrilloAtWork** [comment]
You are correct that the `assert()` will be evaluated only in `debug` builds.
That is a situation that is never expected to happen by logic design, a prerequisite. In some sense the assert is just the documentation of the expectation. With the bonus that in some limited circumstances that expectation is actually tested.
So basically it boils down to the attitude "if this ID is not for PMT fragment, it's your fault and I don't even care what this code is going to do". I express this attitude in the documentation and also, as a courtesy, in the assertion.

**Review by SFBayLaser — COMMENTED** [review]
This looks to be fine to me too.

**Review by SFBayLaser — APPROVED** [review]

**Comment by SFBayLaser** [comment]
AAARGHH!! This went to the master branch.

**Comment by PetrilloAtWork** [comment]
Ahahah! you fell for my trick!!

I.e.: sorry, I did not check and `hub` still does that sometimes/always/when it feels like.

**Pull request merged**
