### PR TITLE
Add larcv output to the stage 1 processing

### PR DESCRIPTION
**Pull request by SFBayLaser**
This pull requests will include the output of larcv files to the stage 1 output. These files are the input to the Machine Learning reconstruction effort.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
So it seems to make it through the actual build process as far as I can tell. There are warnings now which appear to be CMake related?

**Comment by SFBayLaser** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
