### PR TITLE
Feature/rh all pf os [SBN2022B]

### PR DESCRIPTION
**Pull request by rhowell42**
Fhicl lines added to reconstruct each PFO as both a shower and a track. For the upcoming production release (SBN2022b) as discussed in the SBN AI meeting.

### CODE REVIEW

**Comment by rennney** [comment]
@rhowell42 Hi, i changed base for current production (just to check compatibility). It looks like it is based on develop and has all sorts of changes that should not be merged in production (2022B as well). Could you create PR based on current production branch and I will close this one?

**Comment by rhowell42** [comment]
I don't see a branch for the 2022B production, so I merged it with the 2022A production and made a new pull request. Thanks @rennney

**Comment by PetrilloAtWork** [comment]
I do understand @rennney's concern, but I yield to @SFBayLaser on the matter, as I haven't yet fully grasped the model we are following.

**Comment by SFBayLaser** [comment]
I continue to be concerned about the large number of files being modified, I am betting this is a result of the code base when the feature branch was created. I suggest starting over with the latest release along the development branch, introducing on the fhicl file changes that need to be made and then making a new feature branch.

**Comment by rhowell42** [comment]
Argh I thought I got rid of all those commits. Thanks Tracy

**Comment by rennney** [comment]
@rhowell42 @SFBayLaser Hi, this is the old draft I keep for bookkeping at the moment, the correct and working PR is this one : https://github.com/SBNSoftware/icaruscode/pull/424

**Pull request closed without merging**
