### PR TITLE
Removed flash filter from Stage1 standard configuration [`SBN2023A`]

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Twin pull request of #577 but for the production branch. Discussion goes there.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_03 SBNSoftware/sbnanaobj@v09_20_06 SBNSoftware/sbndaq_artdaq_core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_03 SBNSoftware/sbnanaobj@v09_20_06 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Review by SFBayLaser — APPROVED** [review]
Duplicate. I commented in the other one... (PR #577)

**Comment by PetrilloAtWork** [comment]
PR #577 implemented a request to remove `nofilter` configurations since they are completely equivalent to the mainline ones. One of them, `stage1_run2_nofilter_icarus.fcl`, is part of the official production chain and it would be superseded by `stage1_run2_icarus.fcl` (which is already present in this PR).
The question for the production group is if it's ok for this change to happen.

**Comment by PetrilloAtWork** [comment]
Applied the two additional commits like in the development branch (PR #577).
Production will need to update the Stage1 job configuration file name from `stage1_run2_nofilter_icarus.fcl` to `stage1_run2_icarus.fcl`.

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_03 SBNSoftware/sbnanaobj@v09_20_06 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00 SBNSoftware/icarusutil@v09_66_02

**Review by mmrosenberg — APPROVED** [review]

**Pull request merged**
