### PR TITLE
Fix to Stage0 Run1 configuration output path

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Rather than fixing each time in my working area, I do it here.

### CODE REVIEW

**Review by SFBayLaser — APPROVED** [review]
Sorry! I keep thinking that this has been fixed already but I guess not...

**Comment by PetrilloAtWork** [comment]
> Sorry! I keep thinking that this has been fixed already but I guess not...

Or maybe it has, in one of the pull requests still flying around (this is one now!). We'll see.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#61

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
