### PR TITLE
PMT readout simulation

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This is the first implementation of the PMT readout simulation. With its 0-hour testing, it should not be considered production-ready.
This branch also contains a loosely related feature: trigger simulation now also outputs `sbn::ExtraTriggerInfo` data, which may be useful for CAF maker jobs.

The PMT readout simulation requires a trigger simulation, which requires PMT waveforms. Therefore, it is an additional step _after_ the PMT digitisation. This branch does not attempt to integrate it in a production workflow at this time.
The readout simulation happens in steps:
1. digitisation of PMT signals (good old `SimPMTIcarus`)
2. preparation for the trigger simulation: discrimination, combination in pairs, then in windows
3. application of a off-spill trigger logic (currently we are requiring 10 PMT pairs) to define trigger primitives
4. composition of the old waveform content plus noise filler into the waveforms that are supposed to be read out (new `SimPMTreadout` module).

This sequence is encoded in `run_pmtreadoutsimulation_icarus.fcl` job configuration file.
At the end, we are left with a new collection of `raw::OpDetWaveform` (called `daqPMT` in the job above) and the "metadata" collection (`sbn::OpDetWaveformMeta`).
The correct step would be to run the optical reconstruction on the newly created waveforms. A shortcut can be taken with some loss of correctness by using the hits that were already reconstructed on the full waveforms (`opdaq` waveforms, `ophit` hits in `Stage0` configurations) and keep only the ones at the times when readout was active (the metadata is a light-weight data product to obtain that information). Neither pattern is implemented in this branch, which only takes care of the simulation of waveforms.

Because the new module needs to create noise, and in the same way as the DetSim module did, I have detached the PMT noise generation from the core of `PMTsimulationAlg` module into a _art_ tool. This should make it easier to implement a data-driven noise generator in the future, and also can help with the tests by @brucehoward-physics to overlay simulated signals to background data.

The branch is updated to `develop` as of now.

----

Requesting the review of:
* @SFBayLaser especially for the choice of location of files
* @gputnam for the additional part of the trigger information for CAF
* ... not sure if any PMT reconstruction expert wants to comment (@Temigo, @amenegol, @JackSmedley): feel free to add your review if you like.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Review by gputnam — APPROVED** [review]
Looks good to me! Although I can't really speak to the PMT simulation implementation. I'll take a look at what needs to be added to CAF>

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Review by SFBayLaser — APPROVED** [review]
I have no issues with locations.

**Comment by PetrilloAtWork** [comment]
Merge dance: restored the branch pre-merge.

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01 SBNSoftware/sbncode@v09_64_01 SBNSoftware/sbnanaobj@v09_20_01 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_02

**Comment by PetrilloAtWork** [comment]
We have been some merge issues stemming from the facts that:
1. the pull requests to `develop` and production branch are based on the very same branch
2. the `develop` and release branch are now slightly incompatible (that, in GIT terms, means just "incompatible")

In addition, the PR branch is old enough to have conflicts. Our traditional way to address conflicts is to merge the destination branch (e.g. `develop`) into the PR branch, resolve the conflicts, and merge. This process led to a side effect in that the release branch, seeing the same branch as the other PR, now sees the whole `develop` and merging it into the release branch will be a disaster.
On the other end, a commit in the PR branch is the only way (we know) to solve a conflict. A few facts we learned:
1. even using web-based GitHub resolution, a merge/resolution commit is created on the PR branch
2. the branch is modified with that commit even if it is from a fork (i.e. the branch in the fork is modified)

Lesson learned: it is no trivial to create two different GitHub pull requests from the same branch. Well, there are apparently good reasons for that. **Pull requests should not share branches**, the reason being that the conflict resolution on one will affect the remaining pull requests by mixing their target branches.

**Pull request merged**
