### PR TITLE
Update trigger handling for off beam streams

### PR DESCRIPTION
**Pull request by wesketchum**
Added in OffbeamBNB and OffbeamNuMI filter streams/made the rest of the underlying fixes to get the filters to work.

(Also removed single quote deliminators in the trigger decoder tool because my emacs syntax highlighting couldn't handle it and it cost me 30 minutes figuring out that large chunks of code weren't actually commented out/inside quotes. Sorry/not sorry.)

### CODE REVIEW

**Comment by wesketchum** [comment]
This should at least partially resolve #293.

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by mayawos** [comment]
Should L.60-61 in icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_icarus.fcl have both pathOffbeamBNB, pathOffbeamNUMI in the array?

**Comment by wesketchum** [comment]
I was thinking to include it in a separate release? But I may have misunderstood our readiness for that from the discussion on Monday.

**Comment by wesketchum** [comment]
> Should L.60-61 in icaruscode/Decode/fcl/stage0_multiTPC_splitstream_nofilter_icarus.fcl have both pathOffbeamBNB, pathOffbeamNUMI in the array?

Good catch! Just edited that ...

**Comment by mayawos** [comment]
> Looking at the differences I see the addition of the offbeam BNB and NuMi triggers... but are we not also including min bias for both BNB and NuMI as well? Also, if I understand correctly, there is no "unknown" category anymore? Or do we want to deal with those in a later release?

I think we can deal with the unknown category in a later release. I don't think it's usable for production but it can be cleaned up after.
As for min bias, my understanding is that we use the same trigger bits for the NUMI and BNB portion of the min bias run, so currently there's no need to add the min bias BNB and NuMI yet.

**Review by mayawos — APPROVED** [review]

**Review by SFBayLaser — APPROVED** [review]
Ok, I will merge!

**Pull request merged**
