### PR TITLE
Feature/rh all pf os for dev

### PR DESCRIPTION
**Pull request by rhowell42**
Cherry picked just the commits we want from feature/rh_allPFOs

### CODE REVIEW

**Comment by rennney** [comment]
trigger build

**Review by rennney — APPROVED** [review]

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
Technically, it looks ok, although I am not expert enough to detect if anything is missing.

Strategically: this is changing the standard reconstruction chain, meaning that all LArSoft and CAF users will need to take their decision on what is what. *Has this change been advertised to the analysis group stressing that?* If not, I advise that that be done on the next ICARUS analysis meeting or via e-mail if it is more urgent than that.

Also, since I am lazy and uneducated about the difference between showers and tracks, I will still want to know what Pandora would have chosen for me. I imagine that I can get there in a _art_/ROOT file by checking the association of a track or shower to its particle flow object and checking its "particle ID", in a CAF `SRTrack` by checking `SRTrack::ID` or `SRShower::pfp.id` (same thing as Pandora). Please confirm that this or another method are available.

I am stopping this request because of the question in bold above. Once that is addressed, the rest should be good.

**Comment by rhowell42** [comment]
> Strategically: this is changing the standard reconstruction chain, meaning that all LArSoft and CAF users will need to take their decision on what is what. Has this change been advertised to the analysis group stressing that? If not, I advise that that be done on the next ICARUS analysis meeting or via e-mail if it is more urgent than that.
In my previous couple presentations to the analysis group this was stressed and there was much discussion (and conclusions) about implimenting this for the 2022B production.

> Also, since I am lazy and uneducated about the difference between showers and tracks, I will still want to know what Pandora would have chosen for me. I imagine that I can get there in a art/ROOT file by checking the association of a track or shower to its particle flow object and checking its "particle ID", in a CAF SRTrack by checking SRTrack::ID or SRShower::pfp.id (same thing as Pandora). Please confirm that this or another method are available.
One could go about doing this by checking the trackscore variable stored in the pfp branch. > 0.5 and you take the old method reconstructed track, and < 0.5 to take the old method reconstructed shower. I changed the default variables (and cuts) in sbnana to maintain the old pandora method, where you grab the showers and tracks with the proper trackscores

**Review by PetrilloAtWork — APPROVED** [review]

**Comment by PetrilloAtWork** [comment]
I accept the answers from Ryan.
@rennney, please advertise this as a breaking change.
My own analysis code will be very likely broken by this change (well, I just preemptively fixed it), and I expect it not to be the only one. Plus, it's the kind of breakage that you don't notice until you start looking at track/shower distributions.

**Comment by rhowell42** [comment]
I should also mention that this is tied to my PRs in sbnanaobj, sbnana, sbncode, and sbndcode. Those are all required together in the same (or consistent) releases.

https://github.com/SBNSoftware/sbncode/pull/270
https://github.com/SBNSoftware/sbnana/pull/79
https://github.com/SBNSoftware/sbnanaobj/pull/66
https://github.com/SBNSoftware/sbndcode/pull/293

**Comment by rennney** [comment]
Hi @rhowell42, I see most of PRs you've mentioned are still work in progress. Please let me (or @mmrosenberg ) know then they would be ready so we can coordinate the merge.

**Comment by rennney** [comment]
Hi @rhowell42 , since the new production release is coming up I wonder what is the status of relevant sbn PRs. Is there an approximate timeline plan to proceed with the merge of this PR?

**Comment by rhowell42** [comment]
I believe all the relevant sbn PRs have been accepted, at least I've made all the corrections mentioned by experts. I don't really know the approximate timeline for this either, maybe something we should discuss in the sbn analysis meeting soon? @cjbackhouse ?

**Comment by rennney** [comment]
@rhowell42 Hi, we got a merge conflict with recent restructuring of icarus config files. Please have a look

**Comment by rhowell42** [comment]
okay just made & pushed my changes

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Pull request merged**
