### PR TITLE
add simplemerge

### PR DESCRIPTION
**Pull request by yeonjaej**
merging "largeant" and "largeant:droppedMCParticles" for ML reco

### CODE REVIEW

**Comment by yeonjaej** [comment]
@SFBayLaser please review this PR!

**Comment by yeonjaej** [comment]
Bear wrote the SimpleMerge module for SBND refactoring.

**Review by SFBayLaser — APPROVED** [review]
Ok for me as I know this has been extensively tested...

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
