### PR TITLE
Set PFO Characterisation BDT to persist features.

### PR DESCRIPTION
**Pull request by brucehoward-physics**
Marking as draft for now -- I want to make the PRs to do a CI-based test first.

### CODE REVIEW

**Comment by brucehoward-physics** [comment]
Tagged @SFBayLaser and @PetrilloAtWork as reviewers, let me know if I should tag someone else 😅 

This goes along with PRs in `sbncode` and `sbnanaobj`

**Comment by rennney** [comment]
Hi @brucehoward-physics , Putting references to related PRs in description to better track it. Let me know if I missed any 
https://github.com/SBNSoftware/sbnanaobj/pull/74
https://github.com/SBNSoftware/sbncode/pull/291

**Comment by brucehoward-physics** [comment]
Thanks Sergey!

**Review by SFBayLaser — APPROVED** [review]
I am not sure what there is for me to review here... generally I think including this information is a good idea so I certainly approve of that!

**Comment by rennney** [comment]
trigger build

**Pull request merged**
