### PR TITLE
Removed two old versions of PMT decoder module.

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Two old versions of PMT decoder and the tool they used are removed. They have been superseded for longer than one year.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Review by SFBayLaser — APPROVED** [review]
Thank you!

**Comment by PetrilloAtWork** [comment]
I couldn't understand the conflict, and I don't want to spend more time trying to.
I have force-pushed a new commit on top of the current `develop` (maybe while I am writing it has become not current any more?). Please try again, and consider that a force-push was performed (I am not sure whether there are consequences...).

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Pull request merged**
