### PR TITLE
Feature/cerati icarus newg4 dev

### PR DESCRIPTION
**Pull request by cerati**
New refactored G4 for ICARUS.

This PR comes with PRs in icarusalg, sbncode, and eventually sbndcode.

The fcl files for the new refactoring are added (the old fcl files are still there and still working): larg4_icarus*.fcl. Downstream fcl files are detsim_2d_icarus_refactored.fcl and stage0_run2_icarus_mc_refactored.fcl.

There is a new gdml file, that can still be used with the old g4. The new gdml file has no "_" character as it is not compatible with the new G4. This requires the updates to CRT naming conventions in e.g. sorting functions present in this PR.

### CODE REVIEW

**Comment by cerati** [comment]
now created also sbndcode PR: https://github.com/SBNSoftware/sbndcode/pull/390

**Review by jzennamo — APPROVED** [review]
This doesn't seem to impact and "production" fcls but enables us to do a more complete validation. Approved.

**Review by mtorti — APPROVED** [review]

**Review by SFBayLaser — APPROVED** [review]
I suppose it is challenging for G4 to not have tables of values in code but somehow wish there was a better way.... In any case the updates look straightfoward to me so will approve so we can get this in and start validation on larger scale.

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/sbncode#389 SBNSoftware/icarusalg#74

**Pull request merged**
