### PR TITLE
ICARUS configurations for new tool-based interface for CAF selections.

### PR DESCRIPTION
**Pull request by gputnam**
Note -- this is not needed for the upcoming MCP. Depends on https://github.com/SBNSoftware/sbncode/pull/336.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Review by etworcester — APPROVED** [review]
Looks good

**Comment by mmrosenberg** [comment]
trigger build

**Comment by gputnam** [comment]
Closing this PR -- I ended up not thinking this was a good idea.

**Pull request closed without merging**
