### PR TITLE
Improvements and corrections to the Simple Flash Matcher

### PR DESCRIPTION
**Pull request by ikatza**
Main PR:
https://github.com/SBNSoftware/sbncode/pull/300

### CODE REVIEW

**Comment by ikatza** [comment]
Last commit is meant to mitigate: https://github.com/SBNSoftware/sbncode/issues/301

discussed in:
https://github.com/SBNSoftware/sbncode/pull/296

**Review by ggamezdiego — APPROVED** [review]

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbndaq-artdaq-core@offline SBNSoftware/sbn*@release/SBN2022B

**Comment by rennney** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbndaq-artdaq-core@offline SBNSoftware/sbn*@release/SBN2022B SBNSoftware/icaruscode*@release/SBN2022B

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by ikatza** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00

**Pull request merged**
