### PR TITLE
Enabling LArQL for ICARUS 

### PR DESCRIPTION
**Pull request by jzennamo**
This enables the LArQL (addressing https://github.com/SBNSoftware/icaruscode/issues/278) and makes the ICARUS simulation consistent with SBND (see PR https://github.com/SBNSoftware/sbndcode/pull/194)

I'll tag @ggamezdiego to review since I don't see Alessandro M on github

### CODE REVIEW

**Comment by jzennamo** [comment]
trigger build

**Comment by jzennamo** [comment]
This is mostly important for light production outside of the TPC where the electric field strength is low, but it does have an impact on the high dE/dx region too. I have checked the dQ/dx vs. dE/dx for stopping protons with LArQL (red) and without LArQL (blue):

image

When taking the ratio there is a bit of statistical jitter since these aren't the same exact protons but you can see that it is a percent-level effect at very high dE/dx:

image

**Comment by ggamezdiego** [comment]
For completeness, this is what we get for the case of the light in SBND with and without the LArQL model
Captura de pantalla 2021-11-03 a las 16 14 09

**Comment by ggamezdiego** [comment]
BTW, I spoke today with Alessandro and told him about this PR

**Comment by jzennamo** [comment]
@ggamezdiego excellent, thanks for sharing these! It is my understanding that until ICARUS moves to a model similar to SBND this effect won't be seen, is that true?

**Comment by ggamezdiego** [comment]
@jzennamo, the function EFieldAtStep was modified in the ISCalcCorrelated class to be able to distinguish between IN/OUT active volume, by the ISTPC new class. My understanding is that everyone using this class should be sensitive to that

**Review by marcodeltutto — APPROVED** [review]

**Comment by varanini** [comment]
I would approve. How do I do that?

**Review by varanini — APPROVED** [review]

**Review by ggamezdiego — APPROVED** [review]

**Review by mrmooney — APPROVED** [review]
This is fine.  However, in the future, please better communicate proposed changes that impact charge scale (even a small amount) to those leading relevant working groups.  Originally, we were informed that charge scale would not be impacted by this change at all, which was not true.

**Comment by PetrilloAtWork** [comment]
Reference: [SBN DocDB 21270](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=21270).
Is there any comparison on the _light_ in ICARUS?

**Comment by jzennamo** [comment]
I have not, but it modifies the recombination factor, I think in its current implementation this won't have a strong impact on ICARUS, how would you like me to explore this?

**Comment by jzennamo** [comment]
My simulation is fairly low statistics but I'll plot the ratio of LArQL/no LArQL for abs(true X) and dE/dx... plots inbound...

**Comment by jzennamo** [comment]
image

**Comment by jzennamo** [comment]
Here is the light ratio vs dEdx:
image

**Comment by PetrilloAtWork** [comment]
I also suppose there is not a large effect, but I think it's wise to verify.
Maybe my understanding is wrong... here it is.
The new algorithm modifies the recombination factor in regions with low electric field; it is asymptotically matching the old factor for high fields, and the plots in Laura Paulucci presentation show that above 300 V/cm the correction is indistinguishable by eye.
This saves us from issues in between the wire planes, where the field gets to ~900 V/cm.
On the other end, the difference should be large out of the field cage (vanishing electric field).
The recombination factor affects the light in that the recombined electrons produce scintillation light, which should then be quite large _outside_ of the field cage (which your _x_ plot does not cover). Possibly averaging inside and outside of the active volume may wash out the effect.

**Comment by PetrilloAtWork** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
I would try a C.I. test to get a feeling...

**Pull request merged**
