### PR TITLE
New fcl Files to Support Summer Production

### PR DESCRIPTION
**Pull request by gputnam**
title. Depends on:
* https://github.com/SBNSoftware/sbncode/pull/275
* https://github.com/SBNSoftware/icarusalg/pull/57

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
PR #418 has been mentioned as possibly be merged to this one.

**Comment by wesketchum** [comment]
Are these still relevant for the 2022A cycle? And/or should be on develop so they become part of 2022B?

**Comment by wesketchum** [comment]
(looks like already on develop from #423 )

**Comment by SFBayLaser** [comment]
As we move to Run 2... is this PR still required and/or valid?

**Pull request closed without merging**
