### PR TITLE
CAFmaker w/o event weights for detsim2d

### PR DESCRIPTION
**Pull request by jacoblarkin**
New cafmaker fcl based on existing detsim2d cafmaker fcl, but without running systtools or fluxweight. The event weights fail to run on intime cosmic MC so this is needed to make those CAFs.

### CODE REVIEW

**Comment by cerati** [comment]
Thank you @jacoblarkin ! Assuming this has been tested it should go in release asap

**Review by cerati — APPROVED** [review]

**Comment by jacoblarkin** [comment]
I've tested it by making intime cosmic CAFs. Looking at this now, I realize I made the PR for develop. Should I be using SBN2023A instead for the production release?

**Comment by cerati** [comment]
Thanks. About the target branch I'll let @rennney and @mmrosenberg comment

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
The current configurations have:
 * `cafmakerjob_icarus.fcl` as base configuration (no weights)
 * `cafmakerjob_icarus_systtools_and_fluxwgt.fcl` as special configuration with weights

I would prefer to preserve the same pattern for the `detsim2d` variant:
 * `cafmakerjob_icarus_detsim2d.fcl`  with 2D processing (no weights)
 * `cafmakerjob_icarus_detsim2d_systtools_and_fluxwgt.fcl`  with 2D processing and weights

And yes, I am aware that this means that `cafmakerjob_icarus_detsim2d.fcl` changes meaning. I hope we are early enough in the process that we can change that with reduced pain.

Comments welcome.

**Review by PetrilloAtWork — APPROVED** [review]
It looks good to me.
Thank you for your patience, @jacoblarkin.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
In response to the previous question from @jacoblarkin: the target branch is correct. I will be merging all of these changes into the release branch myself when I merge develop into the release branch (we're doing it this way as we need to update the larsoft version used in the release branch)

**Pull request merged**
