### PR TITLE
Accommodate API changes for art 3.12

### PR DESCRIPTION
**Pull request by knoepfel**
Includes removing unnecessary uses of art::Ptr.

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Comment by knoepfel** [comment]
@mmrosenberg, this PR is expected to fail until LArSoft moves to art 3.12, which is likely next week.

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67

**Comment by mmrosenberg** [comment]
trigger build https://github.com/SBNSoftware/icarusalg/pull/67

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67 SBNSoftware/icarusutil@develop

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67 SBNSoftware/icarusutil@develop

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67

**Comment by knoepfel** [comment]
@mmrosenberg, please let me know if there's anything I need to do to help this PR along.

**Comment by mmrosenberg** [comment]
Hi @knoepfel, thanks! Yeah if you could help me figure out why the clang build is failing that would be much appreciated! It looks like the error message from the build log is:

1527: CMake Error at /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_24_1/Linux64bit+3.10-2.17/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
1528:   Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
1529: Call Stack (most recent call first):
1530:   /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_24_1/Linux64bit+3.10-2.17/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
1531:   /cvmfs/larsoft.opensciencegrid.org/products/cmake/v3_24_1/Linux64bit+3.10-2.17/share/cmake-3.24/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
1532:   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_20_00/Modules/private/CetOverrideFindPackage.cmake:174 (_find_package)
1533:   icaruscode/CMakeLists.txt:80 (find_package)

The gcc build is successful, so I'm not sure what's going on here. Any ideas?

**Comment by knoepfel** [comment]
Hmmm...taking a look, @mmrosenberg.

**Comment by knoepfel** [comment]
@mmrosenberg, I understand what happened. LArSoft 09.74 and 09.75 provide an optional dependency on `libtorch` v1_13_1b (through `larpandoracontent`).  That particular version of `libtorch` no longer supports the `c7` Clang compiler.  I will adjust this PR with the appropriate CMake fixes.  Stay tuned.

**Comment by mmrosenberg** [comment]
I see, thank you @knoepfel !!

**Comment by knoepfel** [comment]
@mmrosenberg, required change has been pushed.  Fortunately, because `icaruscode` does not actually use Protobuf, the problem was solved just by removing the offending line in the `CMakeLists.txt` file.

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icarusalg#67

**Comment by mmrosenberg** [comment]
Yes, looks like everything is now working, thanks again @knoepfel!

**Pull request merged**
