### PR TITLE
CSV parsing library update

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This is an update of a CSV parsing library that is currently used for offline trigger decoding and that a coming pull request will use for single photoelectron response data parsing.

This is low level library code, includes unit tests and I don't know who could review it.

This is part of a private branch with a lot of other commits. The branch itself was extensively used with data production-like jobs and I consider it well tested. The changed in this pull request are also involved in those jobs, but they have not been tested standalone.

### CODE REVIEW

**Comment by rennney** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
I made a GitHub edit to fix the issue spotted by Clang.

**Comment by rennney** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
All Clang 7 compilation complains are now expected to be solved.

I needed to compile `icaruscode`, `icarusalg`, `icarusutil` and `icarus_signal_processing`, and finally I found that there was no other issue left.

**Comment by rennney** [comment]
trigger build

**Pull request merged**
