### PR TITLE
Add in SQLite-based tools for normalization procedure

### PR DESCRIPTION
**Pull request by gputnam**

### CODE REVIEW

**Comment by gputnam** [comment]
Note that this PR relies on new SQLite files being put into icarus_data before we can merge it in.

**Review by jedori0228 — APPROVED** [review]

**Comment by jedori0228** [comment]
We can merge this once we add db files into icarus_dadta.

**Comment by jedori0228** [comment]
`icarus_data` has been updated with the tag: v09_59_00, so we can merge this.

**Comment by mmrosenberg** [comment]
trigger build

**Review by mrmooney — APPROVED** [review]
Looks fine to me!

**Pull request merged**
