### PR TITLE
Workaround on FHiCL parameter set bug

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
The bug is discussed in issue #14 of art-framework-suite/fhicl-cpp (https://github.com/art-framework-suite/fhicl-cpp/issues/14). The workaround is that `util::readConfigurationFromArtPrincipal` t emits a warning if an expected configuration is not present, instead of throwing an exception. That puts the load on the caller for checking that the configuration that is needed is actually present (in some of the cases we have seen, it was, so no harm done).

This workaround will cover only the trigger and PMT configuration extraction.
Lookup of the configuration is also performed in some standard LArSoft services (`DetectorClocks` and `DetectorProperties`), where no issue has been reported, and in `CAFMaker` of SBNSoftware/sbncode, that this workaround does not cover.
It _is_ possible to port the same type of workaround in `CAFMaker`. On the other end, this will require a new release of `sbncode`, and it may compete in timeline with a new release of `fhiclcpp` and LArSoft stack with the bug fixed, after which the workaround is not necessary any more. So there is a decision to be taken there.

### CODE REVIEW

**Review by cerati — APPROVED** [review]
works!

**Comment by PetrilloAtWork** [comment]
I _think_ that it is still of interest merging this request, because the issue caused some files to have "corrupted" history saved, and processing those files would still fail.
On the other end, one can also decide that it's too transient and mark the affected data to be junked and reprocessed.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
Although the bug that originated this pull request has been fixed upstream, there are still data files around that are affected by it, and this patch makes the code more robust in my opinion, so I would still like it to be added into a release.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
