### PR TITLE
Triggerv3 code for inclusion in production code

### PR DESCRIPTION
**Pull request by jzettle**
This pull request is meant to correctly handle the new TriggerFragmentV3 that is intended to be used in Run2 to more easily handle the offline POT accounting with our data taking methods. I think this needs to go into the code for use in keep-up processing ASAP. Otherwise we cannot fully switch to running with these corrections in the new trigger fragment in the data as any decoding/processing of the trigger data will not succeed. This is still somewhat a work in progress as I likely need to set up fhicl setups for processing the older data with the TriggerFragmentV2 imagining this is needed to retain the ability to process this data taken before the data switch is made but the idea of this is the standard fhicls now use the new trigger fragment. This likely needs to be merged when the decision is made to fully switch to this fragment definition. This is based off of an older version of icaruscode so I hope not too much needs to be done to make it mergeable

### CODE REVIEW

**Comment by jzettle** [comment]
This will also come with updates to sbncode and the offline version of sbndaq_artdaq_core in order to run the POT accounting giving compatibility to the new fragment and with an idea to where that code can take either TriggerFragmentV2 or TriggerFragmentV3 and still work. I will update this with those PR once I do some initial testing and create those

**Comment by jzettle** [comment]
Okay I changed this to compare to SBN2022B, looking at the conflict now

**Review by PetrilloAtWork — APPROVED** [review]
You have been pre-approved.

**Comment by jzettle** [comment]
New commits set up a set of fhicl files to process any data taken before the official switch to "Run2" with the "Run1" fhicl files

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/sbncode@v09_63_00_02 SBNSoftware/sbndaq-artdaq-core@v1_04_02of0 SBNSoftware/sbnanaobj@v09_20_00_01 SBNSoftware/sbnobj@v09_15_00_01

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/sbncode@v09_63_00_02 SBNSoftware/sbndaq-artdaq-core@v1_04_02of0 SBNSoftware/sbnanaobj@v09_20_00_01 SBNSoftware/sbnobj@v09_15_00_01 LArSoft/lar*@LARSOFT_SUITE_v09_63_00

**Comment by rennney** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
