### PR TITLE
Stage0/Stage1 Fhicl files for ICARUS run 2

### PR DESCRIPTION
**Pull request by SFBayLaser**
NOTE THAT THIS IS A MAJOR REORGANIZATION OF ICARUS STAGE0/STAGE1 FHICL FILES!

We have created the set of fhicl files for run 2 which includes (notably) files for running the 2D drift simulation AND the 2D reconstruction on those files. The general naming convention is `stage0_run2_icarus.fcl` and 'stage1_run2_icarus.fcl' with variants for several special cases. At this time I do not claim to have anticipated every variant that people may want but it is important to get the base set out and included in the next release as a starting point. 

Among the major changes, all the fhicl files previously found in icaruscode/Decode/fcl have been depracated. Any fhicl fiiles remaining in this folder (and subfolders) are no longer installed as part of the build process. Instead, the set of fhicl files needed to run on run 1 and run 2 data have been placed in the fcl/reco folder to be consistent with all other production fhicl files. 

I anticipate it make take some time to completely sort out the details but, as mentioned above, it is important to get this into the latest release.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
trigger build

**Comment by SFBayLaser** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by SFBayLaser** [comment]
Note the last push to this feature branch included modifications to the detector simulation folder. All the pre-existing fhicl files have been moved to the archive/preRun1 subfolder (which is not active) and we are now left with two base fhicl files: "detsim_1d_icarus.fcl" and "detsim_2d_icarus.fcl" where the "1d" and "2d" refer to the 1D and 2D drift simulations respectively. 
Note that for run 2 the stage0 MC processing expects the 2D drift while run1 is still using the 1D.

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Comment by rennney** [comment]
trigger build

**Review by rennney — APPROVED** [review]
This PR will break detsim/reco0/[probably reco1] CI tests. There is a possibility that it will no happen with icarus_data v09_60_00 (that should be pushed prior to this PR), but that is an assumption. 

The PR is ready and should be merged anyway. I will fix CI if needed after. @mmrosenberg , after it is merged there is a big chance that CI tests will fail, so do not worry about it as long as build and unit tests are OK

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
I deleted all of the previous failed CI report comments from FNALbuild as the long comment thread was preventing new trigger build commands from being picked up by the CI system

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
