### PR TITLE
Run-period-dependent channel mapping [SBN2023A]

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This is the production version (i.e. the important version) of PR #620.
They contain the very same commits. :cherries: 

It is imperative that this goes into release as quick as possible once it's ready ~(and now it is _NOT_ ready yet)~ so that production can keep up.

The cable swapping which this request reflects is expected to happen momentarily (in the coming hours), after which we can update the hard-coded run number boundary of the change, and when _that_ commit is also in, dris PR is ready to go.
~Until then, it's draft.~

### CODE REVIEW

**Review by SFBayLaser — APPROVED** [review]
Duplicate entry so ok for me

**Review by mmrosenberg — APPROVED** [review]

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_05 SBNSoftware/sbnanaobj@v09_20_06_02 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00_01 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00_04 SBNSoftware/icarusutil@v09_66_02

**Review by mvicenzi — APPROVED** [review]
I approve as well. Please note production will need to pick up the same `icarus_data` release prepared for #620 .

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_72_00 SBNSoftware/sbncode@v09_72_00_05 SBNSoftware/sbnanaobj@v09_20_06_02 SBNSoftware/sbndaq-artdaq-core@v1_06_00of0 SBNSoftware/sbnobj@v09_16_00_01 SBNSoftware/icarus_signal_processing@v09_63_00_02 SBNSoftware/icarusalg@v09_72_00_04 SBNSoftware/icarusutil@v09_66_02

**Pull request merged**
