### PR TITLE
Updates on the purity module that is used at stage0

### PR DESCRIPTION
**Pull request by cfarnese**
The correction introduced should remove the failures in stage0 due to the purity analysis

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build

**Review by SFBayLaser — APPROVED** [review]
It looks like this will fix the current exceptions so am happy to approve

**Review by francescopoppi — APPROVED** [review]

**Comment by mmrosenberg** [comment]
trigger build

**Comment by cfarnese** [comment]
@SFBayLaser it is not clear to me... why bug? It is not clear to me what is wrong...?

**Comment by SFBayLaser** [comment]
Well, jobs were crashing so was this not fixing a bug? Feel free to re-categorize if you think it needs it

**Comment by cfarnese** [comment]
Ahn ok... sorry @SFBayLaser I misunderstood the tag! I was thinking that you find a bug in my commit!!!! Sorry!!

**Pull request merged**
