### PR TITLE
fhicl files updated for SystTools-based reweight calculator

### PR DESCRIPTION
**Pull request by jedori0228**
This PR adds/updates fhicl files that runs the reweight calculation for  interaction systematic, through modules that are added by  https://github.com/SBNSoftware/sbncode/pull/299.

### CODE REVIEW

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
Please add into `ICARUSv1.ParamHeaders.fcl` a comment referencing the source of the numbers in the configuration file.
Also please rename `ICARUSv1.ParamHeaders.fcl` to a name that hints to systematics and with no dots. E.g. `syst_params_icarus_v1.fcl` or, if you want to preserve the label that is used internally in the name, `syst_params_ICARUSv1.fcl`.

**Review by PetrilloAtWork — APPROVED** [review]
All good, thank you!

**Comment by mmrosenberg** [comment]
trigger build

**Comment by rennney** [comment]
@jedori0228 Hi, what is the status of this PR? I see the sbncode one being closed

**Comment by rennney** [comment]
trigger build

**Pull request merged**
