### PR TITLE
DumpTriggerConfiguration module to print trigger configuration on screen

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This request adds a `DumpTriggerConfiguration` module to print trigger configuration on screen.
The trigger configuration is expected to be stored into a data product, for which a producer module was recently introduced by @ascarpel.

This pull request also contains a few minor tweaks to the output of that data product on screen, and also indentation fixes and a missing function for `BeamBits.h`. Finally, it also moves the name of the trigger data fragment from hard-coded to a parameter.

Since @ascarpel is the original author of the code, I ask for his review.

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
In addition, I would like to solicit a comment by @ascarpel about the dump of the beam gates:
```
   Calibration:
    - Gate Active:               false
    - Drift gate Active:         false
    - MinBias Gate Active:       false
    - MinBias Drift Gate Active: false
    - BeamWidth:                 1600 ns
    - EnableWidth:               2000000 ns
    - EarlyWarningOffset:        0 ns
    - EarlyEarlyWarningOffset:   0 ns
    - PreScale:                  100
    - Period:                    1000000000 ns
```
Here is the fact that `Gate Active` is `false` making all the rest of the information irrelevant? in that case, would it make sense not to dump it not to confuse the reader with pointless information?

**Comment by mmrosenberg** [comment]
trigger build

**Comment by ascarpel** [comment]
@PetrilloAtWork: yes if the `GateActive` parameter is false it means that the trigger is not configured to use that specifc gate. We can choose not to print the output in this case

**Review by ascarpel — APPROVED** [review]
Good to go!

**Comment by PetrilloAtWork** [comment]
With the additional information by @ascarpel, I have "improved" (I hope!) the output. Changes are listed in commit #1903d0d.
Example of output:
```
run: 8470: Basic trigger configuration:
   Use WR time:    true
   WR time offset: 1000000000 ns
  FPGA Configuration:
   Veto Delay:             4000 ns
   MajLevelBeamCryoEAST:   5
   MajLevelEnableCryoEAST: 10
   WindowCryoEAST:         fixed (0)
   MajLevelBeamCryoWEST:   5
   MajLevelEnableCryoWEST: 10
   WindowCryoWEST:         fixed (0)
   MajorityTriggerType:   'majo1or2'
   RunType:               'Majority'
  SPEXI Configuration:
   TPCTriggerDelay: 1.3 ms (3250 x 400 ns)
   BNB:
    - Gate Active:               true
    - Drift gate Active:         true
    - MinBias Gate Active:       true
    - MinBias Drift Gate Active: true
    - BeamWidth:                 2200 ns (plus the veto of 4000 ns)
    - EnableWidth:               2000000 ns
    - EarlyWarningOffset:        900 ns
    - EarlyEarlyWarningOffset:   900 ns
    - MinBias PreScale:          200
   NuMI:
    - Gate Active:               true
    - Drift gate Active:         true
    - MinBias Gate Active:       true
    - MinBias Drift Gate Active: true
    - BeamWidth:                 10100 ns (plus the veto of 4000 ns)
    - EnableWidth:               2000000 ns
    - EarlyWarningOffset:        700 ns
    - EarlyEarlyWarningOffset:   700 ns
    - MinBias PreScale:          60
   Offbeam BNB:
    - Gate Active:               true
    - Drift gate Active:         true
    - MinBias Gate Active:       true
    - MinBias Drift Gate Active: true
    - BeamWidth:                 2200 ns (plus the veto of 4000 ns)
    - EnableWidth:               2000000 ns
    - EarlyWarningOffset:        0 ns
    - EarlyEarlyWarningOffset:   0 ns
    - MinBias PreScale:          20
   Offbeam NuMI:
    - Gate Active:               true
    - Drift gate Active:         true
    - MinBias Gate Active:       true
    - MinBias Drift Gate Active: true
    - BeamWidth:                 10100 ns (plus the veto of 4000 ns)
    - EnableWidth:               2000000 ns
    - EarlyWarningOffset:        0 ns
    - EarlyEarlyWarningOffset:   0 ns
    - MinBias PreScale:          20
   Calibration:
    - Gate Active:               false
```

**Pull request merged**
