### PR TITLE
Discriminated PMT waveforms in Stage0

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
Change in Stage0 configuration (one of them at least...) to produce pre-discriminated PMT waveforms with the threshold set in data for the trigger. The data produced by this additional module suffices to run trigger emulation with that discrimination threshold, even when `raw::OpDetWaveform` collection is dropped (note that this commit does not introduce dropping those waveforms).
The increase in data size observed in a small test where PMT waveforms take 24% of the data is about 0.1% (16 kB/event).
Neutrino simulation got an increase of 2% (66 kB/event).

The two configurations tested with this addition are:
* `stage0_multiTPC_splitstream_nofilter_icarus.fcl`
* `stage0_multiTPC_icarus_MC.fcl`

These configurations were _not_ changed, but rather the definitions they import are.

Content, courtesy of `gh`:
- LVDS width configuration parameter turned into a time
- Stage0 configuration now includes discriminating PMT waveforms

### CODE REVIEW

**Comment by rennney** [comment]
trigger build

**Review by rennney — APPROVED** [review]
Since CI says it is working, I approve

**Comment by rennney** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
I apologise for wasting you reviewers your collective time... I have added the same feature in MC Stage0 processing.
Now I consider the feature complete.

**Review by rennney — APPROVED** [review]

**Review by SFBayLaser — APPROVED** [review]
It is ok with the CI and Gianluca indicates he has tested with standard fhicl files. It is challenging to trust someone with two first names, and two entries in docdb, but will go with his word on this!

**Pull request merged**
