### PR TITLE
Integrate Energy-Scale Calibration Procedure with Data Processing

### PR DESCRIPTION
**Pull request by gputnam**
Depends on https://github.com/LArSoft/lardataalg/pull/35, https://github.com/LArSoft/larreco/pull/45, and https://github.com/SBNSoftware/sbncode/pull/279.

### CODE REVIEW

**Comment by gputnam** [comment]
This update is intended for the fall production. It is not super urgent and also depends on a few upstream updates to larsoft. It deletes the local copies in icaruscode of the Calorimety modules since (I believe) those are no longer used. @SFBayLaser is that ok?

**Comment by jzettle** [comment]
@gputnam @mrmooney What is the status of this and its dependents? We might be very interested in access to this for the trigger efficiency work. Thanks!

**Comment by mmrosenberg** [comment]
trigger build

**Review by SFBayLaser — APPROVED** [review]
I don't see any issues in the updates

**Comment by wesketchum** [comment]
@SFBayLaser so CI failures reported are ok?

**Comment by gputnam** [comment]
@wesketchum @mmrosenberg I found the CI failure cause I think -- just pushed a commit to fix it.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Pull request merged**
