### PR TITLE
Feature/ascarpel pmt calibration

### PR DESCRIPTION
**Pull request by ascarpel**
PR introducing some of the PMT calibration tools. All the changes are (should be) limited to the folder PMT/Calibration.  No breaking changes.

### CODE REVIEW

**Comment by PetrilloAtWork** [comment]
I won't be able to review this until _next_ week (i.e. Dec. 19), sorry.

**Comment by rennney** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Review by SFBayLaser — APPROVED** [review]

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
There are likely things in this branch that need to be updated.
For example, in `decode-pmts.fcl` PMT decoding uses the standard configuration, but it does not call trigger decoding (which the standard configuration requires).

The question for the bosses (@mmrosenberg , @rennney, @SFBayLaser) is whether the best approach is to merge this into `develop` even if it is somehow broken until somebody attempts to use it and is forced to fix it, or to leave it into a branch until then.
I see reasons for both solutions, so I don't really endorse one over the other.

I am "rejecting" the merge to make sure this point above is understood; if the decision is to merge, go ahead — or let me know and I "re-review" it.

**Comment by cerati** [comment]
any update on this PR?

**Comment by rennney** [comment]
@PetrilloAtWork Time passed and I just realized we have this PR. 

1) The description suggests that all changes are limited to PMT/Calibration; however, it is not the case. So the question is if the other changes would have unintended impact.

2) If it has just useful tools  may be we can move it to a separate directory (without CMake) so it is not built? (it might also fix this unit test issue).

**Comment by PetrilloAtWork** [comment]
This PR is a piece of decoration on my workspace, I got used to it.
I do have a question for @mvicenzi though: is this the base of what you are running?
If so, it would mean that @mvicenzi has done work that should be merged here.

**Comment by mvicenzi** [comment]
@PetrilloAtWork Yes, this is basically the code for the PMT gain calibration. I haven't done much development, but I got it to compile and run.

**Comment by rennney** [comment]
trigger build

**Comment by mvicenzi** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by mvicenzi** [comment]
trigger build

**Comment by mvicenzi** [comment]
@rennney I think I fixed the errors from the Dec 16th tests. The last one earlier today complained about a dependency which is not related to this code. I tried merging `develop`. It compiles fine for me locally...

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_66_00

**Comment by mmrosenberg** [comment]
@mvicenzi @rennney the last trigger build failed because the latest version of LArSoft requires a more recent version of nugen than specified in the sbncode dependencies. I re-triggered a build above using the same LArSoft version used in the most recent sbncode release. This will be necessary until the sbn repositories' develop branches are updated for a new sbncode release

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_66_00

**Pull request merged**
