### PR TITLE
Updated trigger decoding scheme

### PR DESCRIPTION
**Pull request by jzettle**
Updated trigger decoding scheme to work with runs taken with new trigger system. This includes additional information added to the online data fragment but this was tested at every step on data runs that do not have this additional fragment information. It has successfully decoded several runs with the new trigger system along with one run I took specifically (8103) in order to test the additional information. This is likely not 100% complete but it is operational and my understanding is this is an urgent need so this should remedy this need.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
Thanks!!!! 
I thought I saw some sbndaqxxx emails flying around, are there any dependencies or is this a single PR needed just for the production branch of icaruscode?
Many thanks again!

**Comment by jzettle** [comment]
@SFBayLaser my apologies I entered the pull request without finishing all my thoughts on the subject. This is dependent on this pull request on the offline branch of `sbndaq_artdaq_core`: https://github.com/SBNSoftware/sbndaq-artdaq-core/pull/50, which I have also added you as a reviewer so you can track each piece.

**Comment by SFBayLaser** [comment]
Ok, thanks!

**Comment by PetrilloAtWork** [comment]
I have added the beam offset correction to the beam timestamp. This may be very important also for physics analyses, so I would rather have it already here. I have set the value in the decoder configuration used for stage0 to be 4 µs (`4000`), which compensates for the veto part of the gate. This may differ from the final implementation, which will likely combine a tool-configuration-defined offset and an offset learnt from the hardware trigger configuration.

I have also made a few technical changes in a separate commit.

I have tested the decoder too, again with a run that did not have the full information in the fragment metadata.
The result for an event of run 8121 is the following:
```trigger ID=43 from source OffbeamBNB at 1650410645.082894656 s on beam gate ID=586 at 1650410645.082893016 s (diff: 1640 ns)
enable gate opened at <n/a> (-1650410645082893017 ns before the gate)
counts from this source: trigger=874523680 beam=252
previous trigger from this source at 1650410641.348324160 s, triggers since: 6, gates since: <n/a> (825767472 from this same source)
most recent trigger was from source unknown at 1650410644.235514640 s (0.847380016 s earlier), and 1461726240 gates from any source have opened since
Correction applied to the timestamps: -36.000000000 s
Location(s) of trigger: Cryo E
West cryostat: 0 triggers
East cryostat: 1 triggers
  west wall:  -------- -------- --------  xx--x-x- -xx-xxx- --------
  east wall:  -------- -------- --------  -------- -------- --------
```
These items appears to be correct:
```trigger ID=43 from source OffbeamBNB at 1650410645.082894656 s on beam gate ID=586 at 1650410645.082893016 s (diff: 1640 ns)
counts from this source: beam=252
previous trigger from this source at 1650410641.348324160 s, triggers since: 6
most recent trigger was at 1650410644.235514640 s (0.847380016 s earlier)
Correction applied to the timestamps: -36.000000000 s
Location(s) of trigger: Cryo E
West cryostat: 0 triggers
East cryostat: 1 triggers
  west wall:  -------- -------- --------  xx--x-x- -xx-xxx- --------
  east wall:  -------- -------- --------  -------- -------- --------
```
These others are not correct:
```enable gate opened at <n/a> (-1650410645082893017 ns before the gate)
counts from this source: trigger=874523680
previous trigger from this source, gates since: <n/a> (825767472 from this same source)
most recent trigger was from source unknown, and 1461726240 gates from any source have opened since
```
As much as I can tell, all these incorrect values (with the exception of the enable gate) are related to the information that Jacob has already pointed out is not present in the fragment metadata of these events. The enable gate information is simply not decoded here.

**Review by PetrilloAtWork — APPROVED** [review]
I have pushed some technical changes and an additional feature that I think we need even for the current data.
The rest is good for me, given that a full review will be performed on the final version (where I won't overlook things like tabs in indentation, commented out code etc).

**Review by SFBayLaser — APPROVED** [review]
I am signing off based on external presentations/discussions.

**Comment by jzettle** [comment]
@SFBayLaser @wesketchum I don't know who enforces this, but I made this pull request on `release/SBN2022A`, not develop so if this is a mistake I can redo or understand what the right approach is.

**Comment by jzettle** [comment]
Sorry another piece I realized when trying to help Anna H. today in her attempt to set up my branches before this is done. I missed patch releases, so my areas depend on icaruscode and sbncode v09_37_02_01 ( `parent icaruscode v09_37_02_01`), so I hope this merge would not overwrite what is in the ups/product_deps for the release/SBN2022A branch

**Comment by SFBayLaser** [comment]
Hi @jzettle, to make it into production it does need to go to the SBN2022A branch so you are right. Ultimately this also needs to go to develop as well since we need for develop to stay current as well (sometime around the end of Summer the develop branch will become the next production release branch point and we don't want code out of step). Right now focus on the production branch, I think the release folks can help with transporting to develop.

**Comment by SFBayLaser** [comment]
With respect to your last comment on being behind the latest on SBN2022A... I think it should be ok. But at the top of the PR page there should be a link to "files changed" and you can cross check that the changes there are what you expect to see.

**Comment by PetrilloAtWork** [comment]
Neither the `ups/product_deps` nor the main `CMakeLists.txt` file appear in the change list, which is how it should be.
Having a pull request behind the head of the branch is normal; GitHub will tell you if there are conflicts (CL=95%?).

**Comment by PetrilloAtWork** [comment]
My (not strong) opinion is that we wait for the final version for that.

**Comment by PetrilloAtWork** [comment]
This branch is being left behind since the one in PR #398 is being chosen instead.
Nevertheless, this branch has the capability of decoding the runs from March 2022 (new trigger kicks in) on, while the new decoder in PR #398 can't decode the ones from when the new trigger was introduced to when SBNSoftware/sbndaq-artdaq-core#54 (which PR #398 depends on) is adopted and used.
This branch (**`feature/jzettle_trigdecoding`**) **should not be deleted**.

**Comment by mmrosenberg** [comment]
Closing this pull request as it was replaced with PR #398

**Pull request closed without merging**
